### ISSUE TITLE
500 when hitting epg.xml

### ISSUE THREAD

**Issue by jmctune** [chkuendig/tvhProxy#6]
Hi there,

Hoping to get some help to get this to work so I can watch twitch streams in Plex.

TVHeadend is setup and I've installed the docker version of this app.

Exec'ing into the container, installing curl and running the following:

```
curl http://localhost:5004/epg.xml

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

My **tvhProxy.env**:

```
cat tvhProxy.env

TVH_BINDADDR="0.0.0.0"
TVH_BINDPORT=5004
TVH_URL="http://tvheadend:9981"
TVH_PROXY_URL="http://tvheadend:5004"
TVH_TUNER_COUNT=6
TVH_WEIGHT=300
TVH_CHUNK_SIZE=1048576
TVH_PROFILE="avlib"
```

TVHeadend has unauthenticated access to all users:

![image](https://user-images.githubusercontent.com/17505625/107309777-b7e38000-6a50-11eb-88eb-dc5a2939837a.png)

I can hit TVHeadend from inside the container:

```
curl http://tvheadend:9981

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<HTML><HEAD>
<TITLE>Redirect</TITLE>
</HEAD><BODY>
Please follow <a href="extjs.html">extjs.html</a>
</BODY></HTML>
```

Not sure what I'm doing wrong..

**Comment by thiagocrepaldi** [comment]
Maybe you have to map some ports on your container and use them as opposed to default ports?

**Comment by jmctune** [comment]
Hey thiagocrepaldi,

All of the app ports are left as default. Both containers are on the same docker network and can directly talk to each other using their DNS names. The tests above were performed inside the tvhProxy container. When trying to make a call using localhost inside the tvhProxy container, I'm seeing the above error. I don't know if it's a communication issue trying to reach out to TVHeadEnd or something else though. :/

Edit: Maybe I don't understand what the TVH_PROXY env var is used for?

**Comment by thiagocrepaldi** [comment]
> TVH_PROXY

That would be my next guess. I dont know how this proxy works,, but I dont think you are using proxy on your setup. let it blank and try again.

**Comment by jmctune** [comment]
No go unfortunately. Rebuilt the container with the below env changes:

```
root@e04fbe7bf06a:/usr/src/app# cat tvhProxy.env

TVH_BINDADDR="0.0.0.0"
TVH_BINDPORT=5004
TVH_URL="http://tvheadend:9981"
TVH_PROXY_URL=""
TVH_TUNER_COUNT=6
TVH_WEIGHT=300
TVH_CHUNK_SIZE=1048576
TVH_PROFILE="avlib"

root@e04fbe7bf06a:/usr/src/app# curl localhost:5004/epg.xml

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

**Comment by jmctune** [comment]
So I just realized that the dotenv file actually doesn't work at all after digging into this more.

```
docker logs tvhproxy

INFO:dotenv.main:Python-dotenv could not find configuration file .env.
INFO:root:Registering upnp:rootdevice (http://172.18.0.25:5004/device.xml)
INFO:root:Sending alive notification for uuid:12345678::upnp:rootdevice
INFO:root:SSDP command NOTIFY * - from 172.18.0.25:1900
INFO:root:SSDP command NOTIFY * - from 172.18.0.25:1900
ERROR:root:An error occured: %sConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=9981): Max retries exceeded with url: /xmltv/channels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f91e679bf40>: Failed to establish a new connection: [Errno 111] Connection refused'))"))
```

These are not the variables I set in the .env file (note the localhost reference). When I export the environment variables manually in my docker-compose script:

```
version: "3.6"
services:
  tvhproxy:
    build: .
    container_name: tvhproxy
    hostname: tvhproxy
    ports:
      - 5005:5004
    networks:
      mynetwork:
    environment:
      TVH_BINDADDR: 0.0.0.0
      TVH_BINDPORT: 5004
      TVH_URL: http://tvheadend:9981
      TVH_TUNER_COUNT: 6
      TVH_WEIGHT: 300
      TVH_CHUNK_SIZE: 1048576
      TVH_PROFILE: avlib

networks:
  mynetwork:
    name: mynetwork
    external: true
```

The variables are actually getting picked up now!

```
docker logs tvhproxy
INFO:root:Registering upnp:rootdevice (http://172.18.0.25:5004/device.xml)
INFO:root:Sending alive notification for uuid:12345678::upnp:rootdevice
INFO:root:SSDP command NOTIFY * - from 172.18.0.25:1900
INFO:root:SSDP command NOTIFY * - from 172.18.0.25:1900
```

I do everything I can to not expose containers to my host, but keep them all traffic isolated inside their own overlay network (and expose them through a reverse proxy for instance). Didn't need to use the PROXY variables in this case.

Pounded my damn head on this for hours.
